services:
  - type: web
    name: wifi-backend-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: AIRTABLE_TOKEN
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false